Update MODULEPATH for hera following Rocky8 upgrade
NOAA-EMC/prepobs pull request #25
Opened 2024-03-18 17:06 UTC by aerorahul

Closes #24

2024-03-18 17:10 UTC, HenryWinterbottom-NOAA commented
LGTM.

2024-03-18 17:10 UTC, HenryRWinterbottom approved these changes

2024-03-18 17:11 UTC, DavidHuber-NOAA approved these changes

2024-03-18 17:15 UTC, aerorahul commented
@HenryWinterbottom-NOAA 
Was this branch installed under `/scratch1/NCEPDEV/global/glopara/git/prepobs/feature-hera-rocky8` tested with cycling in global-workflow?

2024-03-18 17:19 UTC, KateFriedman-NOAA requested changes

2024-03-18 17:19 UTC, KateFriedman-NOAA commented on modulefiles/prepobs_hera.lua
> +--prepend_path("MODULEPATH", "/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/gsi-addon-dev/install/modulefiles/Core")
Why leave the old `MODULEPATH` here?

2024-03-18 17:21 UTC, HenryWinterbottom-NOAA commented
> @HenryWinterbottom-NOAA Was this branch installed under `/scratch1/NCEPDEV/global/glopara/git/prepobs/feature-hera-rocky8` tested with cycling in global-workflow?

No. At least not yet.

2024-03-18 17:30 UTC, aerorahul commented
> > @HenryWinterbottom-NOAA Was this branch installed under `/scratch1/NCEPDEV/global/glopara/git/prepobs/feature-hera-rocky8` tested with cycling in global-workflow?
> 
> No. At least not yet.

Apologies.  I did not frame the q. correctly.  I have corrected the comment.
The branch was installed under the location `/scratch1/NCEPDEV/global/glopara/git/prepobs/feature-hera-rocky8`
The q. is, was this installation tested with cycling in the global-workflow?

2024-03-18 17:59 UTC, HenryWinterbottom-NOAA commented
@aerorahul What specific CI test includes this? I can test right now if I haven't already.

2024-03-18 18:37 UTC, aerorahul commented
> @aerorahul What specific CI test includes this? I can test right now if I haven't already.

any cycled test with GSI will test this.
I suggest [C96_atm3DVar.yaml](https://github.com/NOAA-EMC/global-workflow/blob/develop/ci/cases/pr/C96_atm3DVar.yaml)

2024-03-18 21:57 UTC, HenryWinterbottom-NOAA commented
@aerorahul Which global-workflow submodule is prepobs a part of? I can build and run the 3DVAR test again.

2024-03-19 00:30 UTC, aerorahul commented
> @aerorahul Which global-workflow submodule is prepobs a part of? I can build and run the 3DVAR test again.

See https://github.com/NOAA-EMC/global-workflow/issues/2329#issuecomment-1977306052

2024-03-19 00:31 UTC, HenryWinterbottom-NOAA commented
Thanks.

2024-03-22 18:05 UTC, aerorahul commented on modulefiles/prepobs_hera.lua
> +--prepend_path("MODULEPATH", "/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/gsi-addon-dev/install/modulefiles/Core")
```suggestion
```
Remove commented out lines.

2024-03-22 18:07 UTC, KateFriedman-NOAA approved these changes
Looks good, thanks @aerorahul !

2024-03-22 18:12 UTC, merged